//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBase
{
    
}
namespace MyDerived
{
    using System;
    using System.Xml.Serialization;
    using MyBase;

#if OPT
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeCompileUnitTest", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="TextType", Namespace="http://tempuri.org/myderived.xsd")]
    [XmlRoot("Text", Namespace="http://tempuri.org/myderived.xsd", IsNullable=false)]
    public partial class TextType1 : TextType
    {
    }
#else
    using TextType1 = TextType;
#endif
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeCompileUnitTest", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/mybase.xsd")]
    public partial class TextType
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string languageID;
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
}
namespace MyStatus
{
    using System;
    using System.Xml.Serialization;
    using MyDerived;
    using TextType1 = MyDerived.TextType;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeCompileUnitTest", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/mystatus.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Status", Namespace="http://tempuri.org/mystatus.xsd", IsNullable=false)]
    public partial class StatusType
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/myderived.xsd", Order=0)]
        public TextType1 Text;
    }
}
